#**Linear Algebra for CpE**
##**Laboratory 6 : Matrices** <br>
Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions. <br>
<br>
######**Objectives**
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.



#**Discussion**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

#####**Matrices**
The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$ A = \left\{ \begin{array}\\ x + y \\ 4x - 10y \end{array} \right. \\ B = \left\{ \begin{array}\\ x+y+z \\ 3x -2y -z \\ -x + 4y +2z \end{array} \right. $$
We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$ A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\ B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} $$
So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.<br>

#####**Declaring Matrices**
Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&amp;a_{(0,1)}&amp;\dots&amp;a_{(0,j-1)}\\
a_{(1,0)}&amp;a_{(1,1)}&amp;\dots&amp;a_{(1,j-1)}\\
\vdots&amp;\vdots&amp;\ddots&amp;\vdots&amp;\\
a_{(i-1,0)}&amp;a_{(i-1,1)}&amp;\dots&amp;a_{(i-1,j-1)}
\end{bmatrix}.
$$
We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



## **Categorizing Matrices**

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

######**According to shape**

######**Row and Column Matrices**

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([1, 3, 2]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,3,2]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 3 2]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [3],
    [2]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [3]
 [2]]

Shape:	(3, 1)
Rank:	2



#####**Square Matrices**<br>
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



####**According to element values**<br>
<br>


#####**Null Matrix** 
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
null_mat = np.array([])
null_mat

array([], dtype=float64)

#####**Zero Matrix**
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#####**Ones Matrix**
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#####**Diagonal Matrix**
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:

np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
np.diag([2,3,5])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

#####**Identity Matrix**
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#####**Upper Triangular Matrix**
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

#####**Lower Triangular Matrix**
A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

####**Practice**
1. Given the linear combination below, try to create a corresponding matrix representing it.<br>




>  $$\theta = 5x + 3y - z$$







In [ ]:
row_mat_1D = np.array([5,3,-1])
row_mat_1D

array([ 5,  3, -1])

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

In [ ]:
A = np.array([
    [1, 2, 1],
    [0, 4, -1],
    [0 , 0, -10]
])
describe_mat(A)

Matrix:
[[  1   2   1]
 [  0   4  -1]
 [  0   0 -10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



A has 3 linear equations consists of row and column. There are 3 x sub values x sub 1 to x sub 3. Every x has a value since in algebra the value of x is 1 and the other one that has no value I put a 0 or null. Null is no value. 

3. Given the matrix below, express it as a linear combination in a markdown.<br>


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G = np.diag(G)
G

array([1, 2, 7])

$$ G = \left\{ \begin{array}\\ x+7y+8z \\ 2x +2y +2z \\ 4x + 6y +7z \end{array} \right. $$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 7]])

$$ G = \left\{ \begin{array}\\ 1x_1 \\ x_1 +2x_2  \\ 1x_1 + 2x_2 +7x_3 \end{array} \right. $$

###**Activity**<br><br>
**Task 1**<br>
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix<br>

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

#**Latex Form**
$$ A=\begin{bmatrix} -1 & 2 & 1 & -2 \\ 2 & -4 & -2 & 4 \\ 3 & 2 & -2 & -3 \\ -5 & 4 & -4 & 5\end{bmatrix} \\ $$<br>

$$ B=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 & -3 \\ 3 & -1 & 3\end{bmatrix} \\ $$<br>

$$ C=\begin{bmatrix} 10 & 0 & 10 & 0 \\ 0 & -10 & 0 & -10 \\ 10 & 0 & 10 & 0\end{bmatrix} \\ $$<br>

$$ D=\begin{bmatrix} 0.01 & -2 & 7 \\ 4 & -1.50 & 1.45 \\ -1.3 & 2 & 5.25 \\ 2.5 & 1.5 & -2.75 \end{bmatrix} \\ $$<br>

$$ E=\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix} \\ $$<br>



In [3]:
##Function Area
def mat_desc(matrix): 
  is_square = True if matrix.shape[0] == matrix.shape[1] else False 
  is_empty = matrix.size == 0
  is_zeros_matrix=np.count_nonzero(matrix) == 0
  is_ones_matrix = np.ones(matrix.shape,dtype = int).all() == matrix.all()
  is_identity = (matrix.shape[0] == matrix.shape[1]) and np.allclose(matrix, np.eye(matrix.shape[0]))
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\nIs Empty: {is_empty}\nIs Zeros Matrix:{is_zeros_matrix}\nIs Ones Matrix: {is_ones_matrix}\nIs Identity Matrix:{is_identity}')

In [4]:
## Matrix declarations
A = np.array([
              [-1, 2, 1, -2],
              [2, -4, -2, 4],
              [3, 2, -2, -3],
              [-5, 4, -4, 5]
])

B = np.array([
              [2, 3, 4],
              [1, 2, -3],
              [3, -1, 3]
])

C = np.array([
              [10, 0, 10, 0],
              [0, -10, 0, -10],
              [10, 0, 10, 0]
])

D = np.array([
              [0.01, -2, 7],
              [-4, -1.50, 1.45],
              [-1.3, 2, 5.25],
              [2.5, 1.5, -2.75]
])

E = np.array([
              [0, 0, 0],
              [0, 0, 0],
              [0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]
])

In [ ]:
## Test Areas
mat_desc(A)

Matrix:
[[-1  2  1 -2]
 [ 2 -4 -2  4]
 [ 3  2 -2 -3]
 [-5  4 -4  5]]

Shape:	(4, 4)
Rank:	2
Is Square: True
Is Empty: False
Is Zeros Matrix:False
Is Ones Matrix: True
Is Identity Matrix:False


In [ ]:
mat_desc(B)

Matrix:
[[ 2  3  4]
 [ 1  2 -3]
 [ 3 -1  3]]

Shape:	(3, 3)
Rank:	2
Is Square: True
Is Empty: False
Is Zeros Matrix:False
Is Ones Matrix: True
Is Identity Matrix:False


In [ ]:
mat_desc(C)

Matrix:
[[ 10   0  10   0]
 [  0 -10   0 -10]
 [ 10   0  10   0]]

Shape:	(3, 4)
Rank:	2
Is Square: False
Is Empty: False
Is Zeros Matrix:False
Is Ones Matrix: False
Is Identity Matrix:False


In [ ]:
mat_desc(D)

Matrix:
[[ 0.01 -2.    7.  ]
 [-4.   -1.5   1.45]
 [-1.3   2.    5.25]
 [ 2.5   1.5  -2.75]]

Shape:	(4, 3)
Rank:	2
Is Square: False
Is Empty: False
Is Zeros Matrix:False
Is Ones Matrix: True
Is Identity Matrix:False


In [ ]:
mat_desc(E)

Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(5, 3)
Rank:	2
Is Square: False
Is Empty: False
Is Zeros Matrix:True
Is Ones Matrix: False
Is Identity Matrix:False


**Task 2**<br>
Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:

1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
3. Returns the sum of the matrices.
4. Returns the differen of the matrices.
5. Returns the element-wise multiplication of the matrices.
6. Returns the element-wise division of the matrices.<br>
Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [6]:
np.seterr(divide='ignore', invalid='ignore')
A = np.array([
    [1, -1, -1],
    [-1, 1, -1],
    [-1, -1, 1]
])
 
B = np.array([
    [2, -1, -1],
    [-1, 2, -1],
    [-1, -1, 2]
])

C = np.array([
    [3, -1, -1],
    [-1, 3, -1],
    [-1, -1, 3]
])

D = np.array([
    [4, -1, -1],
    [-1, 4, -1],
    [-1, -1, 4]
])

E = np.array([
    [5, -1, -1],
    [-1, 5, -1],
    [-1, -1, 5]
])
def isScalarMatrix(mat) : 
	# Check all elements 
	# except main diagonal are 
	# zero or not. 
	for i in range(0,len(mat[0])) : 
		for j in range(0,len(mat[0])) : 
			if ((i != j) 
			and (mat[i][j] != 0)) : 
				return False
	# Check all diagonal 
	# elements are same or not. 
	for i in range(0,len(mat[0])-1) : 
		if (mat[i][i] !=
		mat[i + 1][i + 1]) : 
			return False
	return True
 
 
def mat_operations(matrix1, matrix2):
    try:
      name = ""
 
      if(isScalarMatrix(matrix1) and isScalarMatrix(matrix2)):
          name = "Scalar"
      else:
          name = "Matrix"
 
      sum = matrix1 + matrix2
      difference = matrix1 - matrix2
      product = np.multiply(matrix1,matrix2)
      quotient = np.divide(matrix1,matrix2)
      print(f'Sum of {name}:\n{sum}')
      print(f'Difference of {name}:\n{difference}')
      print(f'Product of {name}:\n{product}')
      print(f'Quotient of {name}:\n{quotient}')
    except:
      print("Matrices are not viable for operations")
 
 


In [7]:
mat_operations(A, B)

Sum of Matrix:
[[ 3 -2 -2]
 [-2  3 -2]
 [-2 -2  3]]
Difference of Matrix:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Product of Matrix:
[[2 1 1]
 [1 2 1]
 [1 1 2]]
Quotient of Matrix:
[[0.5 1.  1. ]
 [1.  0.5 1. ]
 [1.  1.  0.5]]


In [8]:
mat_operations(C,D)

Sum of Matrix:
[[ 7 -2 -2]
 [-2  7 -2]
 [-2 -2  7]]
Difference of Matrix:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Product of Matrix:
[[12  1  1]
 [ 1 12  1]
 [ 1  1 12]]
Quotient of Matrix:
[[0.75 1.   1.  ]
 [1.   0.75 1.  ]
 [1.   1.   0.75]]


In [9]:
mat_operations(D, A)

Sum of Matrix:
[[ 5 -2 -2]
 [-2  5 -2]
 [-2 -2  5]]
Difference of Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 3]]
Product of Matrix:
[[4 1 1]
 [1 4 1]
 [1 1 4]]
Quotient of Matrix:
[[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [10]:
mat_operations(B, C)

Sum of Matrix:
[[ 5 -2 -2]
 [-2  5 -2]
 [-2 -2  5]]
Difference of Matrix:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Product of Matrix:
[[6 1 1]
 [1 6 1]
 [1 1 6]]
Quotient of Matrix:
[[0.66666667 1.         1.        ]
 [1.         0.66666667 1.        ]
 [1.         1.         0.66666667]]


In [11]:
isScalarMatrix(A)

False

In [12]:
isScalarMatrix(B)

False

In [13]:
isScalarMatrix(C)

False

In [14]:
isScalarMatrix(D)

False

In [15]:
isScalarMatrix(E)

False