<a href="https://colab.research.google.com/github/maryadriennerdrgz/Linear-Algebra-Compilation/blob/master/Rodriguez_Lab7_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Linear Algebra for CpE**
##**Laboratory 7 : Matrix Operations** <br>
Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more. <br>
<br>
######**Objectives**
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.


#**Discussion**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#**Transposition**<br>
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix} $$<br>
$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$<br>
This can now be achieved programmatically by using np.transpose() or using the T method.

In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)

In [ ]:
AT2 = A.T

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

**Try to create your own matrix (you can try non-squares) to test transposition.**

In [ ]:
## Try out your code here.

#**Dot Product / Inner Product**<br>
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:<br>
<br>
$$X = \begin{bmatrix}x_{(0,0)}&amp;x_{(0,1)}\\ x_{(1,0)}&amp;x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&amp;y_{(0,1)}\\ y_{(1,0)}&amp;y_{(1,1)}\end{bmatrix}$$<br>
The dot product will then be computed as:<br><br>$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} &amp; x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} &amp; x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$
<br>
So if we assign values to $X$ and $Y$:<br><br>$$X = \begin{bmatrix}1&amp;2\\ 0&amp;1\end{bmatrix}, Y = \begin{bmatrix}-1&amp;0\\ 2&amp;2\end{bmatrix}$$
<br>
$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 &amp; 1*0 + 2*2 \\  0*-1 + 1*2 &amp; 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 &amp; 4 \\2 &amp; 2 \end{bmatrix}$$<br>
This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

**Rule 1: The inner dimensions of the two matrices in question must be the same.**<br>
So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:<br>

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$<br>

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.


In [ ]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [ ]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And youcan see that when you try to multiply A and B, it returns ValueError pertaining to matrix shape mismatch.

**Rule 2: Dot Product has special properties**<br>
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:<br>

1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$
<br>

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#**Determinant**<br>

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:$$A = \begin{bmatrix}a_{(0,0)}&amp;a_{(0,1)}\\a_{(1,0)}&amp;a_{(1,1)}\end{bmatrix}$$We can compute for the determinant as:$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$So if we have $A$ as:$$A = \begin{bmatrix}1&amp;4\\0&amp;3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

#**Inverse**<br>

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:$$M = \begin{bmatrix}1&amp;7\\-3&amp;5\end{bmatrix}$$First, we need to get the determinant of $M$.$$|M| = (1)(5)-(-3)(7) = 26$$Next, we need to reform the matrix into the inverse form:$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} &amp; -m_{(0,1)} \\ -m_{(1,0)} &amp; m_{(0,0)}\end{bmatrix}$$So that will be:$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 &amp; -7 \\ 3 &amp; 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} &amp; \frac{-7}{26} \\ \frac{3}{26} &amp; \frac{1}{26}\end{bmatrix}$$For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().

In [ ]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

###**Activity**<br>

**Task 1**<br>
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

**Latex Form**
$$ A=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 & -3 \\ 3 & -1 & 3\end{bmatrix} \\ $$<br>

$$ B=\begin{bmatrix} -1 & 2 & 1  \\ 2 & -4 & -2 \\ 3 & 2 & -2 \end{bmatrix} \\ $$<br>

$$ C=\begin{bmatrix} 0.01 & -2 & 7 \\ 4 & -1.50 & 1.45 \\ -1.3 & 2 & 5.25 \end{bmatrix} \\ $$<br>

**Matrix declarations**

In [ ]:
A = np.array([
              [2, 3, 4],
              [1, 2, -3],
              [3, -1, -3]
              #[-5, 4, -4]
])

B = np.array([
              [-1, 2, 1],
              [2, -4, -2],
              [3, 2, -2]
])

C = np.array([
              [0.01, -2, 7],
              [-4, -1.50, 1.45],
              [-1.3, 2, 5.25]
              #[2.5, 1.5, -2.75, 0.12]
])

**Shapes**

In [ ]:
def mat_desc(matrix): 
  is_square = True if matrix.shape[0] == matrix.shape[1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}')

In [ ]:
mat_desc(A)

Matrix:
[[ 2  3  4]
 [ 1  2 -3]
 [ 3 -1 -3]]

Shape:	(3, 3)


In [ ]:
mat_desc(B)

Matrix:
[[-1  2  1]
 [ 2 -4 -2]
 [ 3  2 -2]]

Shape:	(3, 3)


In [ ]:
mat_desc(C)

Matrix:
[[ 0.01 -2.    7.  ]
 [-4.   -1.5   1.45]
 [-1.3   2.    5.25]]

Shape:	(3, 3)


#1.  $A \cdot B \neq B \cdot A$

In [ ]:
x = A @ B
print ("A * B:\n",x)

A * B:
 [[ 16   0 -12]
 [ -6 -12   3]
 [-14   4  11]]


In [ ]:
y = B @ A
print ("B * A:\n",y)

B * A:
 [[  3   0 -13]
 [ -6   0  26]
 [  2  15  12]]


In [ ]:
z = np.array_equal(x,y,)
print ("A * B = B * A:",z)

A * B = B * A: False


#**2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$**

In [ ]:
q = A @ (B @ C)
print ("A * (B * C):\n",q)

A * (B * C):
 [[ 15.76 -56.    49.  ]
 [ 44.04  36.   -43.65]
 [-30.44  44.   -34.45]]


In [ ]:
w = (A @ B) @ C
print ("(A * B) * C:\n",w)

(A * B) * C:
 [[ 15.76 -56.    49.  ]
 [ 44.04  36.   -43.65]
 [-30.44  44.   -34.45]]


In [ ]:
e = np.array_equal(w,q)
print ("A * (B * C) = (A * B) * C: ",e)

A * (B * C) = (A * B) * C:  False


#**3. $A\cdot(B+C) = A\cdot B + A\cdot C$**

In [ ]:
m = A @ (B + C)
print ("A * (B + C):\n",m)

A * (B + C):
 [[ -1.18  -0.5   27.35]
 [-10.09 -23.    -2.85]
 [ -6.07  -6.5   14.8 ]]


In [ ]:
i = A@B + A@C
print ("A * B + A * C:\n",i)

A * B + A * C:
 [[ -1.18  -0.5   27.35]
 [-10.09 -23.    -2.85]
 [ -6.07  -6.5   14.8 ]]


In [ ]:
d = np.array_equal(i,m)
print ("A * (B + C) = A * B + A * C: ",d)

A * (B + C) = A * B + A * C:  False


#**4. $(B+C)\cdot A = B\cdot A + C\cdot A$**

In [ ]:
xx = (B + C) @ A
print ("(B + C) * A:\n",xx)

(B + C) * A:
 [[ 22.02 -10.97 -27.96]
 [-11.15 -16.45  10.15]
 [ 17.15   9.85 -14.95]]


In [ ]:
yy = B@A + C@A
print ("B * A + C * A:\n",yy)

B * A + C * A:
 [[ 22.02 -10.97 -27.96]
 [-11.15 -16.45  10.15]
 [ 17.15   9.85 -14.95]]


In [ ]:
zz = np.array_equal(xx,yy)
print ("A * (B + C) = B * A + C * A: ",zz)

A * (B + C) = B * A + C * A:  False


#**5. $A\cdot I = A$**

In [ ]:
print ("Matrix A:\n",A)

Matrix A:
 [[ 0.01 -2.    7.  ]
 [-4.   -1.5   1.45]
 [-1.3   2.    5.25]]


In [ ]:
A_inv = np.linalg.inv(A)
print ("Inverse of A:\n",A_inv)

Inverse of A:
 [[ 0.140625 -0.078125  0.265625]
 [ 0.09375   0.28125  -0.15625 ]
 [ 0.109375 -0.171875 -0.015625]]


In [ ]:
nope = np.array(A @ np.linalg.inv(A), dtype=int)
nope

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
bee = np.array_equal(A,nope)
print ("A * I = A: ",bee)

A * I = A:  False


#**6. $A\cdot \emptyset = \emptyset$**

In [ ]:
zeroo = np.zeros(A.shape)
zeroo

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zero = A.dot(np.zeros(A.shape))
print ("A * ∅: \n",zero)

A * ∅: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
true = np.array_equal(zero,zeroo)
print ("A * ∅ = ∅: ",true)

A * ∅ = ∅:  True
